import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/components/frame';
import { TopButton } from '@/components/common';

const notoSans = Noto_Sans_KR({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'], // 원하는 굵기
});

export const metadata: Metadata = {
  title: 'YD-Industry',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${notoSans.variable} antialiased`}>
        <Header />
        <div>{children}</div>
        <TopButton />
        {/* <QuickInquiry /> TODO: 빠른 문의 적용 필요?*/}
        <Footer />
      </body>
    </html>
  );
}
