import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/components/frame';
import { TopButton } from '@/components/common';
import { getCompanyInfo } from '@/api/componyInfo';

const notoSans = Noto_Sans_KR({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'YD-Industry',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const companyInfo = await getCompanyInfo();

  return (
    <html lang='ko'>
      <body className={`${notoSans.variable} antialiased`}>
        <Header />
        <div>{children}</div>
        <TopButton />
        <Footer companyInfo={companyInfo} />
      </body>
    </html>
  );
}
