import type { Metadata } from 'next';
import '@/app/globals.css';
import SideBar from '@/components/admin/SideBar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui';

export const metadata: Metadata = {
  title: 'YD-Industry',
  description: 'Generated by create next app',
};

export default function AdminDashBoardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className='flex min-h-screen'>
        <SideBar />
        <main className='flex-1 p-6'>
          <SidebarTrigger />
          {children}
        </main>
      </div>
    </SidebarProvider>
  );
}
